spring.application.name=taskflow
spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow
spring.datasource.username=taskflow_user
spring.datasource.password=${TASKFLOW_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

#Endpoints que expongo en web
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
#Habilita la exposicion de informacion de la linea anterior
info.app.name=Taskflow Sprinboot App
info.app.description=Task Application made by CarlosO with SpringBoot
info.app.version=1.0.0